"""Contains all the necessary configuration variables.

All configuration is done inside this file.

Todo:
    - Add License boilerplate
"""

import os

SERIAL_PORT = "Com4"
CAMERA_ID = 1

CLASS_ID = 0
CAMERA_FRAME_WIDTH = 1280
CAMERA_FRAME_HEIGHT = 800

OBJECT_POSITION = [600, 0, 50]
MIN_CAPTURE_HEIGHT = 50
MAX_CAPTURE_HEIGHT = 300
CAPTURE_STEPS = 7

GREEN_MIN_THRESHOLD = 0.14 # Default: 0.14
GREEN_MAX_THRESHOLD = 0.2 # Default: 0.2

MASK_CONTOUR_SMOOTHING = 9
MASK_CONTOUR_MIN_SIZE = 1.0/50.0
MASK_TIGTHEN_DISTANCE = 7
MASK_SMOOTH_DISTANCE = 11
MASK_ENLARGE_DISTANCE = 3

GREEN_SPILL_COLOR = (40, 110, 49)
GREEN_SPILL_MIN_THRESHOLD = 0.98
GREEN_SPILL_MAX_THRESHOLD = 0.99
GREEN_SPILl_SMOOTH_DISTANCE = 11
GREEN_SPILL_REDUCTION = 0.6

MODEL_MULTIPLY_MESSAGE_MASK_AUGMENTATION = 5
MODEL_MULTIPLY_MESSAGE_BACKGROUND_ASSIGNMENT = 2
MODEL_MULTIPLY_MESSAGE_IMAGE_AUGMENTATION = 3
MODEL_MASK_CUTOUT_PROB = 0.5
MODEL_MASK_CUTOUT_ITERATIONS = (1, 3)
MODEL_MASK_CUTOUT_SIZE = 0.5
MODEL_PERSPECTIVE_MIN_TRANSFORMATION = 0.00
MODEL_PERSPECTIVE_MAX_TRANSFORMATION = 0.2
MODEL_MIN_SCALE = 0.5
MODEL_MAX_SCALE = 1.5
MODEL_MIN_ROT = -180
MODEL_MAX_ROT = 180
MODEL_PERCENTAGE_FLIP = 0.5

# This is the area of the picture filled by the object
MODEL_MIN_RELATIVE_SIZE = 0.1
MODEL_MAX_RELATIVE_SIZE = 1.0

# Number of image multiplications which will be augmented (1 is direct pass)
TRAINING_AUGEMENTATION_MULTIPLY = 3
TEST_TRAING_SPLIT = 0.15

PREVENT_BLURRED_OBJECTS = True
        